# Generated by Django 4.2.2 on 2023-07-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_pessoa_projeto_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/external_images/cadeiras_educacao'),
        ),
    ]
