# Generated by Django 4.2.2 on 2023-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_alter_cadeira_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
