# Generated by Django 4.2.2 on 2023-07-05 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_alter_cadeira_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='autor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='categoria',
            field=models.ManyToManyField(related_name='artigos', to='portifolio.categoria'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cadeiras/'),
        ),
    ]
