# Generated by Django 4.2.2 on 2023-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_artigo_destaque_artigo_imagem_artigo_visitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(default='your_default_value'),
        ),
    ]
