# Generated by Django 4.2.2 on 2023-07-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('profissional', 'Profissional')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], null=True),
        ),
    ]
