# Generated by Django 4.2.2 on 2024-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0013_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='numero_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitante',
            name='sexo',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher'), ('jovem', 'Jovem'), ('crianca', 'Criança')], default='homem', max_length=20),
        ),
    ]
