# Generated by Django 4.2.2 on 2024-02-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0014_visitante_numero_visitas_visitante_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='faixa_etaria',
            field=models.CharField(choices=[('adulto', 'Adulto'), ('jovem', 'Jovem'), ('crianca', 'Criança')], default='adulto', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='sexo',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher')], default='homem', max_length=20),
        ),
    ]
