# Generated by Django 4.2.2 on 2024-02-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0015_visitante_faixa_etaria_alter_visitante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='numero_visitas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
